name: ffs
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.3.2
  cloud_firestore: ^3.1.17
  flutter_svg: ^1.0.3
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  get: ^4.6.5
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.1
  uuid: ^3.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/montserrat_thin.ttf
          weight: 100
        - asset: assets/font/montserrat_extra_light.ttf
          weight: 200
        - asset: assets/font/montserrat_light.ttf
          weight: 300
        - asset: assets/font/montserrat_regular.ttf
          weight: 400
        - asset: assets/font/montserrat_medium.ttf
          weight: 500
        - asset: assets/font/montserrat_semi_bold.ttf
          weight: 600
        - asset: assets/font/montserrat_bold.ttf
          weight: 700
        - asset: assets/font/montserrat_extra_bold.ttf
          weight: 800
        - asset: assets/font/montserrat_black.ttf
